# Generated by Django 4.2.3 on 2023-07-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertpost',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='concertpost',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='concertpost',
            name='duration_day',
        ),
        migrations.RemoveField(
            model_name='concertpost',
            name='time',
        ),
    ]
