# Generated by Django 4.2.3 on 2023-07-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_concertpost_age_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events')),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': '1. Tadbirlar',
            },
        ),
    ]
