# Generated by Django 4.2.3 on 2023-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertpost',
            options={'verbose_name': 'Konsert ', 'verbose_name_plural': '1. Konsertlar'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Tadbir ', 'verbose_name_plural': '2. Tadbirlar'},
        ),
        migrations.RemoveField(
            model_name='concertpost',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='concertpost',
            name='description',
        ),
        migrations.AlterField(
            model_name='concertpost',
            name='date',
            field=models.DateField(verbose_name='Konsert sanasi'),
        ),
        migrations.AlterField(
            model_name='concertpost',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Konsert nomi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True, verbose_name="Qisqa ma'lumot"),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='images/events', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Nomi'),
        ),
    ]
