# Generated by Django 4.2.3 on 2023-07-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_concertpost_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertpost',
            name='language',
            field=models.CharField(choices=[("O'zbek", "O'zbek"), ('Rus', 'Rus')], default="O'zbek", max_length=10, verbose_name='Post chiqariladigan til'),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[("O'zbek", "O'zbek"), ('Rus', 'Rus')], default="O'zbek", max_length=10, verbose_name='Post chiqariladigan til'),
        ),
    ]
